[build]
publish = "public"
command = "python sync_projects.py && hugo"

[context.production.environment]
HUGO_VERSION = "0.68.3"

[dev]
framework = "hugo"

[functions]
directory = "crons"

[build.environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"