[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"

[dev]
framework = "hugo"

[[redirects]]
  from = "https://justine.mehdibaha.com/*"
  to = "/game.html"
  status = 200
  force = true
